version: "3.3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
      
  prometheus-node:
    image: prom/node-exporter
    container_name: prometheus-node
    ports:
      - "9095:9095"      
    pid: host

  web:
    build: .
    ports:
      - "5000:5000"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus