global:
  scrape_interval: 10s

  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['host.docker.internal:9093']

scrape_configs:
  - job_name: flask_app
    static_configs:
      - targets: ["host.docker.internal:5000"]

  - job_name: prometheus
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9095"]
